# Upgrade all dependencies in requirements.txt by:
# docker run -v ./:/files --rm -it $(grep "FROM ghcr" Dockerfile | awk '{print $2}') bash
# $ apt-get update
# $ apt-get install -y --no-install-recommends python3-pip git
# $ pip3 install uv --break-system-packages
# $ cd /files
# $ uv pip compile -U pyproject.toml -o requirements.txt --group force
[project]
name = "force-base-image-installation"
version = "0.2.0"
description = "Installation project for force-base-image-installation"
requires-python = ">=3.14"
dependencies = [
  # Required by OpenCV.
  "numpy",
  "scipy",
]

# The force dependency group is an internal technicality that avoids
# reinstalling Python packages we already have from Ubuntu packages.
# When updating:
#   GDAL version: update "gdal==<version>" below and run "uv pip compile" as
#                 described at the top of this file.
#   Ubuntu version: update the other package versions below and run
#                   "uv pip compile" as described at the top of this file.
[dependency-groups]
force = [
  # GDAL version must match the FROM line in Dockerfile.
  "gdal==3.13.0",
  # Some python3-packages from Ubuntu are installed, keep those versions.
  "numpy==2.3.5",
]
